language: csharp
solution: MustacheCs.sln
install:
  - nuget restore MustacheCs.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MustacheCs.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MustacheCs.test/bin/Release/MustacheCs.test.dll
